In [72]:
#!pip install polars

In [73]:
from IPython import get_ipython
get_ipython().run_line_magic('reset', '-f')

# Import datasets

In [74]:
import polars as pl

general_information = pl.read_csv('data/general_information_bkp.csv', infer_schema_length=None, ignore_errors=True)
type_and_level = pl.read_csv('data/type_and_level_bk.csv', infer_schema_length=None, ignore_errors=True)
geographical_facilities = pl.read_csv('data/geographical_facilities_bkp.csv', infer_schema_length=None, ignore_errors=True)
buildings_and_library = pl.read_csv('data/buildings_and_library.csv', infer_schema_length=None, ignore_errors=True)
compliance1 = pl.read_csv('data/compliance_1_bkp.csv', infer_schema_length=None, ignore_errors=True)
compliance2 = pl.read_csv('data/compliance_2_bkp.csv', infer_schema_length=None, ignore_errors=True)
compliance3 = pl.read_csv('data/compliance_3_bkp.csv', infer_schema_length=None, ignore_errors=True)
compliance4 = pl.read_csv('data/compliance_4_bkp.csv', infer_schema_length=None, ignore_errors=True)
divisions = pl.read_csv('data/divisions_bkp.csv', infer_schema_length=None, ignore_errors=True)
districts = pl.read_csv('data/districts_bkp.csv', infer_schema_length=None, ignore_errors=True)
thanas = pl.read_csv('data/thanas_bkp.csv', infer_schema_length=None, ignore_errors=True)
pbgsi_institutions = pl.read_csv('data/pbgsi_7000_ins_bkp.csv', infer_schema_length=None, ignore_errors=True)
institute_type = pl.read_csv('configs/institution_type.csv', infer_schema_length=None, ignore_errors=True)
student_type = pl.read_csv('configs/student_types.csv', infer_schema_length=None, ignore_errors=True)
divisions = pl.read_csv('data/divisions_bkp.csv', infer_schema_length=None, ignore_errors=True)
districts = pl.read_csv('data/districts_bkp.csv', infer_schema_length=None, ignore_errors=True)
thanas = pl.read_csv('data/thanas_bkp.csv', infer_schema_length=None, ignore_errors=True)
approval_status = pl.read_csv('configs/approval_status.csv', infer_schema_length=None, ignore_errors=True)
boards = pl.read_csv('configs/boards.csv', infer_schema_length=None, ignore_errors=True)
boundary_types = pl.read_csv('configs/boundary_type.csv', infer_schema_length=None, ignore_errors=True)
emis_submission_types = pl.read_csv('configs/emis_submission_types.csv', infer_schema_length=None, ignore_errors=True)
fiscal_years = pl.read_csv('configs/fiscal_years.csv', infer_schema_length=None, ignore_errors=True)
geographical_location_types = pl.read_csv('configs/geographical_locations_type.csv', infer_schema_length=None, ignore_errors=True)
highest_levels = pl.read_csv('configs/higest_levels.csv',infer_schema_length=None, ignore_errors=True)
management_type = pl.read_csv('configs/management_types.csv', infer_schema_length=None, ignore_errors=True)
mpo_status = pl.read_csv('configs/mpo_status.csv', infer_schema_length=None, ignore_errors=True)
ownership_types = pl.read_csv('configs/ownership_type.csv', infer_schema_length=None, ignore_errors=True)
pass_rate_types = pl.read_csv('configs/pass_rate_type.csv', infer_schema_length=None, ignore_errors=True)
sexual_harassment_committee_activity_type = pl.read_csv('configs/sexual_harassment_committee_activity_type.csv', infer_schema_length=None, ignore_errors=True)
students_attendance_types = pl.read_csv('configs/students_attendance_type.csv', infer_schema_length=None, ignore_errors=True)
teachers_attendance_types = pl.read_csv('configs/teachers_attendance_type.csv', infer_schema_length=None, ignore_errors=True)
technical_types = pl.read_csv('configs/technical_type.csv', infer_schema_length=None, ignore_errors=True)
ward_type = pl.read_csv('configs/ward_type.csv', infer_schema_length=None, ignore_errors=True)

Filter General Information only for **submitted** institutions

In [75]:

result = general_information.filter( pl.col(general_information['submitted'].name)==True, pl.col(general_information['establishment_date'].name).str.strptime(pl.Date, "%d-%m-%Y").dt.year()>2000)

result.head()

shape: (5, 51)
┌────────┬────────────┬────────────┬────────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ id     ┆ institutio ┆ institutio ┆ address_vi ┆ … ┆ submitted ┆ comments ┆ forward_b ┆ forward_b │
│ ---    ┆ n_name_ban ┆ n_name_eng ┆ llage_hold ┆   ┆ _app_vers ┆ ---      ┆ ack_deo_m ┆ ack_useo_ │
│ i64    ┆ gla        ┆ lish       ┆ ing        ┆   ┆ ion       ┆ str      ┆ sg        ┆ msg       │
│        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---       ┆          ┆ ---       ┆ ---       │
│        ┆ str        ┆ str        ┆ str        ┆   ┆ str       ┆          ┆ str       ┆ str       │
╞════════╪════════════╪════════════╪════════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 187115 ┆ মোশারফ      ┆ MOSHARAF   ┆ AZIZPUR    ┆ … ┆ 2.4.1     ┆ null     ┆ null      ┆ null      │
│        ┆ হোসেন প্রধান ┆ HOSSAIN    ┆            ┆   ┆           ┆          ┆           ┆           │
│        ┆ কলেজ       ┆ PRODHAN    ┆            ┆   ┆           ┆          ┆           ┆           │
│        ┆            ┆ COLLE…     ┆            ┆   ┆           ┆          ┆           ┆           │
│ 187119 ┆ সৈয়দ মোশারফ ┆ SYED       ┆ Mohesadi   ┆ … ┆ 2.4.2     ┆ null     ┆ null      ┆ null      │
│        ┆ রশিদা       ┆ MOSARAF    ┆            ┆   ┆           ┆          ┆           ┆           │
│        ┆ একাডেমী     ┆ ROSIDA     ┆            ┆   ┆           ┆          ┆           ┆           │
│        ┆            ┆ ACADEMY    ┆            ┆   ┆           ┆          ┆           ┆           │
│ 187124 ┆ কবি নজরুল   ┆ KABI       ┆ DAULATPUR  ┆ … ┆ 2.4.2     ┆ null     ┆ null      ┆ null      │
│        ┆ উচ্চ বিদ্যালয় ┆ NAZRUL     ┆            ┆   ┆           ┆          ┆           ┆           │
│        ┆            ┆ HIGH       ┆            ┆   ┆           ┆          ┆           ┆           │
│        ┆            ┆ SCHOOL,    ┆            ┆   ┆           ┆          ┆           ┆           │
│        ┆            ┆ NAWAB…     ┆            ┆   ┆           ┆          ┆           ┆           │
│ 187128 ┆ আখতার       ┆ AKTER      ┆ KUMRAKHALI ┆ … ┆ 2.4.1     ┆ null     ┆ null      ┆ null      │
│        ┆ মোশ্বেদ কৃষি ┆ MORSHED    ┆            ┆   ┆           ┆          ┆           ┆           │
│        ┆ প্রযুক্তি …   ┆ AGRICULTUR ┆            ┆   ┆           ┆          ┆           ┆           │
│        ┆            ┆ TECHN…     ┆            ┆   ┆           ┆          ┆           ┆           │
│ 187134 ┆ ইউসেপ      ┆ UCEP       ┆ PLOT #7,   ┆ … ┆ 2.2.1     ┆ null     ┆ null      ┆ null      │
│        ┆ হেসামুদ্দিন   ┆ HESAMUDDIN ┆ BLOCK #B,  ┆   ┆           ┆          ┆           ┆           │
│        ┆ টেকনিক্যাল   ┆ TECHNICAL  ┆ SATHMOSJID ┆   ┆           ┆          ┆           ┆           │
│        ┆ স…         ┆ SCHO…      ┆ …          ┆   ┆           ┆          ┆           ┆           │
└────────┴────────────┴────────────┴────────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [76]:

result = general_information.group_by(
    (pl.col(general_information['establishment_date'].name).str.strptime(pl.Date,'%d-%m-%Y').dt.year()).alias("year"),
    maintain_order=True
).len(name="Institutions Count")

result.head()

shape: (5, 2)
┌──────┬────────────────────┐
│ year ┆ Institutions Count │
│ ---  ┆ ---                │
│ i32  ┆ u32                │
╞══════╪════════════════════╡
│ null ┆ 5788               │
│ 1995 ┆ 1623               │
│ 1998 ┆ 1061               │
│ 1979 ┆ 308                │
│ 1996 ┆ 870                │
└──────┴────────────────────┘

In [77]:


general_information = general_information.join(type_and_level, left_on=general_information['eiin'].name, right_on=type_and_level['eiin'].name, how="inner", suffix='_type_and_level')
general_information = general_information.join(geographical_facilities, left_on=general_information['eiin'].name, right_on=geographical_facilities['eiin'].name, how="inner", suffix='_geographical_facilities')
general_information = general_information.join(compliance1, left_on=general_information['eiin'].name, right_on=compliance1['eiin'].name, how='inner', suffix='_compliance1')
general_information = general_information.join(compliance2, left_on=general_information['eiin'].name, right_on=compliance2['eiin'].name, how='inner', suffix='_compliance2')
general_information = general_information.join(compliance3, left_on=general_information['eiin'].name, right_on=compliance3['eiin'].name, how='left', suffix='_compliance3')
general_information = general_information.join(compliance4, left_on=general_information['eiin'].name, right_on=compliance4['eiin'].name, how='inner', suffix='_compliance4')

In [78]:
general_information.head()

shape: (5, 369)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id     ┆ institutio ┆ institutio ┆ address_v ┆ … ┆ seventh_g ┆ eighth_gr ┆ ninth_gra ┆ tenth_gra │
│ ---    ┆ n_name_ban ┆ n_name_eng ┆ illage_ho ┆   ┆ rade_book ┆ ade_books ┆ de_books_ ┆ de_books_ │
│ i64    ┆ gla        ┆ lish       ┆ lding     ┆   ┆ s_provide ┆ _provided ┆ provided  ┆ provided  │
│        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ d         ┆ ---       ┆ ---       ┆ ---       │
│        ┆ str        ┆ str        ┆ str       ┆   ┆ ---       ┆ i64       ┆ i64       ┆ i64       │
│        ┆            ┆            ┆           ┆   ┆ i64       ┆           ┆           ┆           │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 200841 ┆ গওহর আলম   ┆ GAWHAR     ┆ RAMJANNOG ┆ … ┆ 18        ┆ 17        ┆ 0         ┆ 0         │
│        ┆ নিন্ম       ┆ ALAM       ┆ OR        ┆   ┆           ┆           ┆           ┆           │
│        ┆ মাধ্যমিক     ┆ JUNIOR     ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ বিদ্যা…      ┆ SCHOOL     ┆           ┆   ┆           ┆           ┆           ┆           │
│ 227570 ┆ হার্ভার্ড স্কুল  ┆ HARVARD    ┆ JHENAIDAH ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ এন্ড        ┆ SCHOOL AND ┆ SADAR     ┆   ┆           ┆           ┆           ┆           │
│        ┆ কলেজ,ঝিনা…  ┆ COLLAGE,   ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ JH…        ┆           ┆   ┆           ┆           ┆           ┆           │
│ 231559 ┆ কেরাব পাবলিক ┆ KAROBO     ┆ WORAD-4,  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ হাইস্কুল      ┆ PUBLIC     ┆ KANCHAN   ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ HIGH       ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ SCHOOL     ┆           ┆   ┆           ┆           ┆           ┆           │
│ 194780 ┆ ক্রোকিরচর   ┆ KROKIR     ┆ KROKIR    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ আকিমুনেছা    ┆ CHAR       ┆ CHAR      ┆   ┆           ┆           ┆           ┆           │
│        ┆ বালিকা দাখ…   ┆ AKIMON     ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ NESA       ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ BALIKA…    ┆           ┆   ┆           ┆           ┆           ┆           │
│ 198357 ┆ খোদা বকস    ┆ K B HIGH   ┆ RAMNAGAR  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│        ┆ মাধ্যমিক     ┆ SCHOOL     ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ বিদ্যালয়, রা… ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [79]:


general_information = general_information.join(institute_type, left_on=general_information['institution_type'].name, right_on=institute_type['institute_type_id'].name, how='inner', suffix='_institution_type')

In [80]:
general_information.head()

shape: (5, 371)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id     ┆ institutio ┆ institutio ┆ address_v ┆ … ┆ ninth_gra ┆ tenth_gra ┆ institute ┆ institute │
│ ---    ┆ n_name_ban ┆ n_name_eng ┆ illage_ho ┆   ┆ de_books_ ┆ de_books_ ┆ _type_nam ┆ _type_nam │
│ i64    ┆ gla        ┆ lish       ┆ lding     ┆   ┆ provided  ┆ provided  ┆ e         ┆ e_en      │
│        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│        ┆ str        ┆ str        ┆ str       ┆   ┆ i64       ┆ i64       ┆ str       ┆ str       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 200841 ┆ গওহর আলম   ┆ GAWHAR     ┆ RAMJANNOG ┆ … ┆ 0         ┆ 0         ┆ স্কুল       ┆ SCHOOL    │
│        ┆ নিন্ম       ┆ ALAM       ┆ OR        ┆   ┆           ┆           ┆           ┆           │
│        ┆ মাধ্যমিক     ┆ JUNIOR     ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ বিদ্যা…      ┆ SCHOOL     ┆           ┆   ┆           ┆           ┆           ┆           │
│ 227570 ┆ হার্ভার্ড স্কুল  ┆ HARVARD    ┆ JHENAIDAH ┆ … ┆ null      ┆ null      ┆ স্কুল এন্ড   ┆ SCHOOL    │
│        ┆ এন্ড        ┆ SCHOOL AND ┆ SADAR     ┆   ┆           ┆           ┆ কলেজ      ┆ AND       │
│        ┆ কলেজ,ঝিনা…  ┆ COLLAGE,   ┆           ┆   ┆           ┆           ┆           ┆ COLLEGE   │
│        ┆            ┆ JH…        ┆           ┆   ┆           ┆           ┆           ┆           │
│ 231559 ┆ কেরাব পাবলিক ┆ KAROBO     ┆ WORAD-4,  ┆ … ┆ null      ┆ null      ┆ স্কুল       ┆ SCHOOL    │
│        ┆ হাইস্কুল      ┆ PUBLIC     ┆ KANCHAN   ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ HIGH       ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ SCHOOL     ┆           ┆   ┆           ┆           ┆           ┆           │
│ 194780 ┆ ক্রোকিরচর   ┆ KROKIR     ┆ KROKIR    ┆ … ┆ null      ┆ null      ┆ মাদ্রাসা      ┆ MADRASHA  │
│        ┆ আকিমুনেছা    ┆ CHAR       ┆ CHAR      ┆   ┆           ┆           ┆           ┆           │
│        ┆ বালিকা দাখ…   ┆ AKIMON     ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ NESA       ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ BALIKA…    ┆           ┆   ┆           ┆           ┆           ┆           │
│ 198357 ┆ খোদা বকস    ┆ K B HIGH   ┆ RAMNAGAR  ┆ … ┆ null      ┆ null      ┆ স্কুল       ┆ SCHOOL    │
│        ┆ মাধ্যমিক     ┆ SCHOOL     ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ বিদ্যালয়, রা… ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [81]:
general_information = general_information.join(student_type, left_on=general_information['student_type'].name, right_on=student_type['student_type_id'].name, how='inner', suffix='_student_type')
general_information = general_information.join(divisions, left_on=general_information['address_division'].name, right_on=divisions['division_id'].name, how='inner', suffix='_division')
general_information = general_information.join(districts, left_on=general_information['address_district'].name, right_on=districts['district_id'].name, how='inner', suffix='_district')
general_information = general_information.join(thanas, left_on=general_information['address_thana'].name, right_on=thanas['thana_id'].name, how='inner', suffix='_thana')
general_information = general_information.join(geographical_location_types, left_on=geographical_facilities['geographical_position'].name, right_on=geographical_location_types['geographical_location_id'].name, how='inner', suffix='_geographical_location_type')

In [83]:
general_information.head(5)

shape: (5, 389)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id     ┆ institutio ┆ institutio ┆ address_v ┆ … ┆ thana_nam ┆ district_ ┆ city_corp ┆ geographi │
│ ---    ┆ n_name_ban ┆ n_name_eng ┆ illage_ho ┆   ┆ e_bn      ┆ id        ┆ ---       ┆ cal_locat │
│ i64    ┆ gla        ┆ lish       ┆ lding     ┆   ┆ ---       ┆ ---       ┆ str       ┆ ion_name  │
│        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ str       ┆ i64       ┆           ┆ ---       │
│        ┆ str        ┆ str        ┆ str       ┆   ┆           ┆           ┆           ┆ str       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 200841 ┆ গওহর আলম   ┆ GAWHAR     ┆ RAMJANNOG ┆ … ┆ শ্যামনগর    ┆ 59        ┆ null      ┆ সমতল      │
│        ┆ নিন্ম       ┆ ALAM       ┆ OR        ┆   ┆           ┆           ┆           ┆           │
│        ┆ মাধ্যমিক     ┆ JUNIOR     ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ বিদ্যা…      ┆ SCHOOL     ┆           ┆   ┆           ┆           ┆           ┆           │
│ 227570 ┆ হার্ভার্ড স্কুল  ┆ HARVARD    ┆ JHENAIDAH ┆ … ┆ ঝিনাইদহ    ┆ 26        ┆ null      ┆ সমতল      │
│        ┆ এন্ড        ┆ SCHOOL AND ┆ SADAR     ┆   ┆ সদর       ┆           ┆           ┆           │
│        ┆ কলেজ,ঝিনা…  ┆ COLLAGE,   ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ JH…        ┆           ┆   ┆           ┆           ┆           ┆           │
│ 231559 ┆ কেরাব পাবলিক ┆ KAROBO     ┆ WORAD-4,  ┆ … ┆ রূপগঞ্জ     ┆ 43        ┆ null      ┆ সমতল      │
│        ┆ হাইস্কুল      ┆ PUBLIC     ┆ KANCHAN   ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ HIGH       ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ SCHOOL     ┆           ┆   ┆           ┆           ┆           ┆           │
│ 194780 ┆ ক্রোকিরচর   ┆ KROKIR     ┆ KROKIR    ┆ … ┆ কালকিনি    ┆ 34        ┆ null      ┆ সমতল      │
│        ┆ আকিমুনেছা    ┆ CHAR       ┆ CHAR      ┆   ┆           ┆           ┆           ┆           │
│        ┆ বালিকা দাখ…   ┆ AKIMON     ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ NESA       ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ BALIKA…    ┆           ┆   ┆           ┆           ┆           ┆           │
│ 198357 ┆ খোদা বকস    ┆ K B HIGH   ┆ RAMNAGAR  ┆ … ┆ ঝিনাইদহ    ┆ 26        ┆ null      ┆ সমতল      │
│        ┆ মাধ্যমিক     ┆ SCHOOL     ┆           ┆   ┆ সদর       ┆           ┆           ┆           │
│        ┆ বিদ্যালয়, রা… ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [87]:
general_information['institute_type_name_en'].head()

shape: (10,)
Series: 'institute_type_name_en' [str]
[
	"SCHOOL"
	"SCHOOL AND COLLEGE"
	"SCHOOL"
	"MADRASHA"
	"SCHOOL"
	"SCHOOL"
	"MADRASHA"
	"MADRASHA"
	"SCHOOL"
	"SCHOOL"
]

In [88]:


general_information = general_information.with_columns([
    pl.col('institution_type').alias('generalized_institution_type_id'),
    pl.col('institute_type_name_en').alias('generalized_institution_type_name_en')
])

In [89]:
general_information.head()

shape: (5, 391)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id     ┆ institutio ┆ institutio ┆ address_v ┆ … ┆ city_corp ┆ geographi ┆ generaliz ┆ generaliz │
│ ---    ┆ n_name_ban ┆ n_name_eng ┆ illage_ho ┆   ┆ ---       ┆ cal_locat ┆ ed_instit ┆ ed_instit │
│ i64    ┆ gla        ┆ lish       ┆ lding     ┆   ┆ str       ┆ ion_name  ┆ ution_typ ┆ ution_typ │
│        ┆ ---        ┆ ---        ┆ ---       ┆   ┆           ┆ ---       ┆ e_i…      ┆ e_n…      │
│        ┆ str        ┆ str        ┆ str       ┆   ┆           ┆ str       ┆ ---       ┆ ---       │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ i64       ┆ str       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 200841 ┆ গওহর আলম   ┆ GAWHAR     ┆ RAMJANNOG ┆ … ┆ null      ┆ সমতল      ┆ 1         ┆ SCHOOL    │
│        ┆ নিন্ম       ┆ ALAM       ┆ OR        ┆   ┆           ┆           ┆           ┆           │
│        ┆ মাধ্যমিক     ┆ JUNIOR     ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ বিদ্যা…      ┆ SCHOOL     ┆           ┆   ┆           ┆           ┆           ┆           │
│ 227570 ┆ হার্ভার্ড স্কুল  ┆ HARVARD    ┆ JHENAIDAH ┆ … ┆ null      ┆ সমতল      ┆ 2         ┆ SCHOOL    │
│        ┆ এন্ড        ┆ SCHOOL AND ┆ SADAR     ┆   ┆           ┆           ┆           ┆ AND       │
│        ┆ কলেজ,ঝিনা…  ┆ COLLAGE,   ┆           ┆   ┆           ┆           ┆           ┆ COLLEGE   │
│        ┆            ┆ JH…        ┆           ┆   ┆           ┆           ┆           ┆           │
│ 231559 ┆ কেরাব পাবলিক ┆ KAROBO     ┆ WORAD-4,  ┆ … ┆ null      ┆ সমতল      ┆ 1         ┆ SCHOOL    │
│        ┆ হাইস্কুল      ┆ PUBLIC     ┆ KANCHAN   ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ HIGH       ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ SCHOOL     ┆           ┆   ┆           ┆           ┆           ┆           │
│ 194780 ┆ ক্রোকিরচর   ┆ KROKIR     ┆ KROKIR    ┆ … ┆ null      ┆ সমতল      ┆ 4         ┆ MADRASHA  │
│        ┆ আকিমুনেছা    ┆ CHAR       ┆ CHAR      ┆   ┆           ┆           ┆           ┆           │
│        ┆ বালিকা দাখ…   ┆ AKIMON     ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ NESA       ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ BALIKA…    ┆           ┆   ┆           ┆           ┆           ┆           │
│ 198357 ┆ খোদা বকস    ┆ K B HIGH   ┆ RAMNAGAR  ┆ … ┆ null      ┆ সমতল      ┆ 1         ┆ SCHOOL    │
│        ┆ মাধ্যমিক     ┆ SCHOOL     ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ বিদ্যালয়, রা… ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [90]:
import importlib

condition = pl.col(general_information['generalized_institution_type_id'].name)==3

general_information = general_information.with_columns([
    pl.when(condition)
    .then(pl.lit(2))
    .otherwise(pl.col(general_information['generalized_institution_type_id'].name))
    .alias('generalized_institution_type_id'),
    
    pl.when(condition)
    .then(pl.lit('SCHOOL AND COLLEGE'))
    .otherwise(pl.col(general_information['generalized_institution_type_name_en'].name))
    .alias('generalized_institution_type_name_en')
])

In [91]:
general_information.head()

shape: (5, 391)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id     ┆ institutio ┆ institutio ┆ address_v ┆ … ┆ city_corp ┆ geographi ┆ generaliz ┆ generaliz │
│ ---    ┆ n_name_ban ┆ n_name_eng ┆ illage_ho ┆   ┆ ---       ┆ cal_locat ┆ ed_instit ┆ ed_instit │
│ i64    ┆ gla        ┆ lish       ┆ lding     ┆   ┆ str       ┆ ion_name  ┆ ution_typ ┆ ution_typ │
│        ┆ ---        ┆ ---        ┆ ---       ┆   ┆           ┆ ---       ┆ e_i…      ┆ e_n…      │
│        ┆ str        ┆ str        ┆ str       ┆   ┆           ┆ str       ┆ ---       ┆ ---       │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆ i64       ┆ str       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 200841 ┆ গওহর আলম   ┆ GAWHAR     ┆ RAMJANNOG ┆ … ┆ null      ┆ সমতল      ┆ 1         ┆ SCHOOL    │
│        ┆ নিন্ম       ┆ ALAM       ┆ OR        ┆   ┆           ┆           ┆           ┆           │
│        ┆ মাধ্যমিক     ┆ JUNIOR     ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ বিদ্যা…      ┆ SCHOOL     ┆           ┆   ┆           ┆           ┆           ┆           │
│ 227570 ┆ হার্ভার্ড স্কুল  ┆ HARVARD    ┆ JHENAIDAH ┆ … ┆ null      ┆ সমতল      ┆ 2         ┆ SCHOOL    │
│        ┆ এন্ড        ┆ SCHOOL AND ┆ SADAR     ┆   ┆           ┆           ┆           ┆ AND       │
│        ┆ কলেজ,ঝিনা…  ┆ COLLAGE,   ┆           ┆   ┆           ┆           ┆           ┆ COLLEGE   │
│        ┆            ┆ JH…        ┆           ┆   ┆           ┆           ┆           ┆           │
│ 231559 ┆ কেরাব পাবলিক ┆ KAROBO     ┆ WORAD-4,  ┆ … ┆ null      ┆ সমতল      ┆ 1         ┆ SCHOOL    │
│        ┆ হাইস্কুল      ┆ PUBLIC     ┆ KANCHAN   ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ HIGH       ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ SCHOOL     ┆           ┆   ┆           ┆           ┆           ┆           │
│ 194780 ┆ ক্রোকিরচর   ┆ KROKIR     ┆ KROKIR    ┆ … ┆ null      ┆ সমতল      ┆ 4         ┆ MADRASHA  │
│        ┆ আকিমুনেছা    ┆ CHAR       ┆ CHAR      ┆   ┆           ┆           ┆           ┆           │
│        ┆ বালিকা দাখ…   ┆ AKIMON     ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ NESA       ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆ BALIKA…    ┆           ┆   ┆           ┆           ┆           ┆           │
│ 198357 ┆ খোদা বকস    ┆ K B HIGH   ┆ RAMNAGAR  ┆ … ┆ null      ┆ সমতল      ┆ 1         ┆ SCHOOL    │
│        ┆ মাধ্যমিক     ┆ SCHOOL     ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ বিদ্যালয়, রা… ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [92]:
student_type.head()

shape: (3, 3)
┌─────────────────┬───────────────────┬──────────────────────┐
│ student_type_id ┆ student_type_name ┆ student_type_name_en │
│ ---             ┆ ---               ┆ ---                  │
│ i64             ┆ str               ┆ str                  │
╞═════════════════╪═══════════════════╪══════════════════════╡
│ 1               ┆ ছেলে              ┆ Boy                  │
│ 2               ┆ মেয়ে              ┆ Girl                 │
│ 3               ┆ সহশিক্ষা            ┆ Co-education         │
└─────────────────┴───────────────────┴──────────────────────┘

In [93]:
report1 = (
    general_information.lazy()
    .group_by('generalized_institution_type_name_en')
    .agg([
         pl.len().alias('total'),
         (pl.col('student_type')==1).sum().alias('total_boys'),
         (pl.col('student_type')==2).sum().alias('total_girls'),
         (pl.col('student_type')==3).sum().alias('co-education')
    ])
)

report1_df = report1.collect()
report1_df.head(100)

shape: (5, 5)
┌─────────────────────────────────┬───────┬────────────┬─────────────┬──────────────┐
│ generalized_institution_type_n… ┆ total ┆ total_boys ┆ total_girls ┆ co-education │
│ ---                             ┆ ---   ┆ ---        ┆ ---         ┆ ---          │
│ str                             ┆ u32   ┆ u32        ┆ u32         ┆ u32          │
╞═════════════════════════════════╪═══════╪════════════╪═════════════╪══════════════╡
│ TECHNICAL AND VOCATIONAL        ┆ 1759  ┆ 7          ┆ 100         ┆ 1652         │
│ MADRASHA                        ┆ 11552 ┆ 352        ┆ 1431        ┆ 9769         │
│ SCHOOL AND COLLEGE              ┆ 6223  ┆ 35         ┆ 834         ┆ 5354         │
│ QAOMI MADRASHA                  ┆ 5844  ┆ 2545       ┆ 2112        ┆ 1187         │
│ SCHOOL                          ┆ 25414 ┆ 335        ┆ 3094        ┆ 21985        │
└─────────────────────────────────┴───────┴────────────┴─────────────┴──────────────┘